import Flac.Native.Bits
import Flac.Native.Codec
import Flac.Native.Crc
import Flac.Native.Decode
import Flac.Native.Utf8Num
import Flac.Native.Heuristics
import Flac.Native.Emit
import Flac.Native.Lpc
import Flac.Native.Reader
import Flac.Native.Md5
import Flac.Native.Rice
import Flac.Native.Fixed
import Flac.Native.Subframe
import Flac.Native.Frame
import Flac.Native.Stereo
import Flac.Native.Stream
import Flac.Spec.Bits
import Flac.Spec.Crc
import Flac.Spec.Decode
import Flac.Spec.Fixed
import Flac.Spec.Frame
import Flac.Spec.Lpc
import Flac.Spec.Heuristics
import Flac.Spec.Emit
import Flac.Spec.Reader
import Flac.Spec.Rice
import Flac.Spec.Stereo
import Flac.Spec.Stream
import Flac.Spec.Subframe
import Flac.Spec.Utf8Num

/-! # Soundproof — a formally verified FLAC codec in pure Lean 4 -/
