name = "vinyl"
version = "0.1.0"
defaultTargets = ["Flac", "FlacTest", "flactest"]

[[lean_lib]]
name = "Flac"

[[lean_lib]]
name = "FlacTest"

[[lean_exe]]
name = "flactest"
root = "FlacTest.Main"

[[lean_exe]]
name = "vinyl"
root = "Vinyl"
