#!/usr/bin/env bash
# Provenance + integrity of the COMMITTED corpus. Run from fuzz/.
#
#   scripts/corpus_verify.sh            verify sha256 of every committed seed
#                                       against MANIFEST.toml + the size gate;
#                                       fail on a mismatch or an unmanifested file
#   scripts/corpus_verify.sh --update   (re)write MANIFEST.toml from disk
#
# external/ and evolved/ are gitignored working sets and are NOT manifested. The
# curated seed set ships as corpus/seeds.tar.gz (make corpus / make corpus-pack);
# this verifies its UNPACKED contents. The gate bounds the extracted set against
# gross pollution -- the large syncWindow/parThreshold seeds put the honest total
# near 17 MB (6.6 MB as the committed archive), so the gate is 24 MB.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
MAN="corpus/MANIFEST.toml"
GATE_MB=24

committed_files() {
  find corpus -type f \
    -not -path 'corpus/external/*' -not -path 'corpus/*/evolved/*' \
    -not -name 'MANIFEST.toml' -not -name 'sources.toml' -not -name '.gitattributes' \
    -not -name 'seeds.tar.gz' \
    | sort
}

if [ "${1:-}" = "--update" ]; then
  { echo "# Generated by scripts/corpus_verify.sh --update -- sha256 + size of every"
    echo "# committed seed. Provenance is the sub-directory (see corpus/sources.toml)."
    echo "schema = 1"
    while IFS= read -r f; do
      sha=$(sha256sum "$f" | cut -d' ' -f1)
      sz=$(stat -c%s "$f")
      printf '\n[[seed]]\npath = "%s"\nsha256 = "%s"\nbytes = %s\nsource = "%s"\n' \
        "${f#corpus/}" "$sha" "$sz" "$(dirname "${f#corpus/}")"
    done < <(committed_files)
  } > "$MAN"
  echo "wrote $MAN ($(committed_files | wc -l) seeds)"
  exit 0
fi

[ -f "$MAN" ] || { echo "no $MAN -- run: scripts/corpus_verify.sh --update" >&2; exit 1; }
fail=0
# every committed file present in the manifest with a matching sha256
while IFS= read -r f; do
  rel="${f#corpus/}"
  sha=$(sha256sum "$f" | cut -d' ' -f1)
  if ! grep -q "\"$rel\"" "$MAN"; then
    echo "UNMANIFESTED: $rel" >&2; fail=1; continue
  fi
  grep -A2 "\"$rel\"" "$MAN" | grep -q "$sha" || { echo "SHA MISMATCH: $rel" >&2; fail=1; }
done < <(committed_files)

total=$(committed_files | xargs -r stat -c%s | awk '{s+=$1} END{print s+0}')
if [ "$total" -gt $((GATE_MB * 1024 * 1024)) ]; then
  echo "SIZE GATE: committed corpus $((total/1024/1024))MB > ${GATE_MB}MB" >&2; fail=1
fi
[ "$fail" = 0 ] && echo "corpus OK ($(committed_files | wc -l) seeds, $((total/1024))KB)"
exit "$fail"
