# mk/lean.mk — Lean side of the build: run `lake build` in the repo, compile
# its generated C (IR) into libvinyl.{fuzz,afl}.a, and probe the exported
# symbol surface so a link failure becomes one clear line, not a wall of
# undefined references.

# ---- lake stamp ---------------------------------------------------------
# `lake build` is gated on a stamp over every .lean source, so an unchanged
# tree does not re-invoke lake on every `make`. The stamp is touched only
# after a successful build.
LEAN_SRCS := $(shell find $(REPO)/Flac $(REPO)/FlacTest -name '*.lean' 2>/dev/null)
LAKE_STAMP := $(GEN)/.lake.stamp

$(LAKE_STAMP): $(LEAN_SRCS)
	@mkdir -p $(@D)
	@echo "  lake build ($(REPO))"
	@cd $(REPO) && $(LAKE_BIN) build
	@touch $@

.PHONY: lean-ir
lean-ir: $(LAKE_STAMP) $(GEN)/vinyl_symbols.h

# ---- generated symbol map ----------------------------------------------
# vinyl_symbols.h defines HAVE_<UPPERCASED_SYMBOL> 1 for every lp_vinyl_*
# token that appears in the IR. common/vinyl_parallel.c and friends guard
# their risky externs with #ifdef HAVE_..., so a fortified codec that drops
# an internal symbol degrades gracefully to "feature unavailable" instead of
# failing the whole link.
$(GEN)/vinyl_symbols.h: $(LAKE_STAMP)
	@mkdir -p $(@D)
	@{ echo '/* generated by mk/lean.mk -- do not edit */'; \
	   echo '#ifndef VINYL_SYMBOLS_H'; echo '#define VINYL_SYMBOLS_H'; \
	   grep -rho '\blp_vinyl_[A-Za-z0-9_]*' $(IR_DIR) --include='*.c' 2>/dev/null \
	     | sort -u | sed 's/.*/#define HAVE_\U&\E 1/'; \
	   echo '#endif'; } > $@

# ---- check-symbols: hard gate on the entry points the wrappers REQUIRE ---
# Distinct from the #ifdef-guarded optional surface: these are the symbols the
# rig cannot run without. Grep every lp_vinyl_* the wrappers *call* out of
# common/*.c (minus the ones only referenced in an #ifdef HAVE_ guard, which
# vinyl_parallel handles itself) and fail before linking with the exact name.
# Phase 7A: the STABLE @[export vinyl_*] entry-point names (FlacTest/FuzzGen.lean),
# not the mangled lp_vinyl_Flac_* forms. The harness links these, so a Lean-internal
# rename fails `lake build` on the export wrapper (unknown identifier) BEFORE it can
# reach the link -- the harness no longer depends on Lean's name mangling. The three
# ___boxed forms the harness still uses (pcmBytes/pcmBytesRange/encodePcm16Fast) stay
# on their compiler-generated mangled names -- Lean does not emit a ___boxed for a
# def-alias -- but their plain stable siblings below gate the same functions, so a
# rename is still caught here.
REQUIRED_SYMS := \
  vinyl_decode_bytes vinyl_decode_arrays vinyl_read_meta vinyl_decode_option \
  vinyl_decode_pcm16a vinyl_decode_reference vinyl_pcm_bytes vinyl_pcm_bytes_range \
  vinyl_encode vinyl_encode_pcm16_fast vinyl_encode_pcm16_cfg vlean_unchecked_encode \
  vinyl_default_chooser vlean_md5 \
  vinyl_emit_fast vinyl_encode_pcm16 vinyl_deinterleave vinyl_pcm16_of_byte_list

# Phase 7B: gate on symbols the codec archive actually DEFINES (llvm-nm on
# libvinyl.fuzz.a, T/t entries), not on tokens that merely APPEAR in the IR source
# -- grepping .c matched comments/strings and passed a referenced-but-undefined
# symbol that then failed at link. nm is the ground truth of the linked surface.
.PHONY: check-symbols
check-symbols: $(BUILD)/lib/libvinyl.fuzz.a
	@defined=$$(llvm-nm --defined-only $(BUILD)/lib/libvinyl.fuzz.a 2>/dev/null \
	           | awk '$$2 ~ /^[TtWw]$$/ {print $$3}' | sort -u); \
	missing=""; \
	for s in $(REQUIRED_SYMS); do \
	  echo "$$defined" | grep -qx "$$s" || missing="$$missing $$s"; \
	done; \
	if [ -n "$$missing" ]; then \
	  echo "FATAL: fortified codec does not DEFINE required symbols (llvm-nm on libvinyl.fuzz.a):" >&2; \
	  for s in $$missing; do echo "         $$s" >&2; done; \
	  exit 1; \
	fi; \
	echo "check-symbols: all $(words $(REQUIRED_SYMS)) required lp_vinyl_* defined in libvinyl.fuzz.a."

# ---- IR compile + archive ----------------------------------------------
# Exclude executable-root modules that define `int main` (FlacTest/Main.c, the
# CLI/test entry). Their `main` is a STRONG symbol; left in libvinyl.a it would
# out-link the fuzzer driver's own main and the binary would run the Vinyl CLI
# instead of libFuzzer/AFL. The codec functions (lp_vinyl_*) live in other
# modules, so nothing the wrappers call is lost -- check-symbols proves it.
IR_SRCS_ALL  := $(sort $(wildcard $(IR_DIR)/*.c $(IR_DIR)/*/*.c $(IR_DIR)/*/*/*.c $(IR_DIR)/*/*/*/*.c))
IR_MAIN_SRCS := $(shell grep -rl '^int main' $(IR_DIR) --include='*.c' 2>/dev/null)
IR_SRCS      := $(filter-out $(IR_MAIN_SRCS),$(IR_SRCS_ALL))
ir_objname = $(subst /,_,$(patsubst $(IR_DIR)/%,%,$(1:.c=.o)))

# One IR compile rule per (flavour x file).
define IR_RULE
$(BUILD)/obj/fuzz/vinyl/$(call ir_objname,$(1)): $(1)
	@mkdir -p $$(@D)
	$(CLANG) $(CFLAGS_FUZZ) $(CFLAGS_IR_EXTRA) -I$(LEAN_INC) -MMD -MP -c $$< -o $$@

$(BUILD)/obj/afl/vinyl/$(call ir_objname,$(1)): $(1)
	@mkdir -p $$(@D)
	$(AFL_CC) $(CFLAGS_AFL) $(CFLAGS_IR_EXTRA) -I$(LEAN_INC) -MMD -MP -c $$< -o $$@

# covfuzz IR (Phase 1): the same -O2 fuzzer flavour PLUS source-based coverage.
# A 4th compile of the IR, gated behind the .covfuzz targets (nothing depends on
# IR_OBJS_COVFUZZ unless a coverage binary is requested), so the default build
# never pays for it.
$(BUILD)/obj/covfuzz/vinyl/$(call ir_objname,$(1)): $(1)
	@mkdir -p $$(@D)
	$(CLANG) $(CFLAGS_COVFUZZ) $(CFLAGS_IR_EXTRA) -I$(LEAN_INC) -MMD -MP -c $$< -o $$@

# cmplog IR (Phase 3E-afl): AFL toolchain + AFL_LLVM_CMPLOG=1. Gated behind the
# .cmplog targets (opt-in `make cmplog`), so the default build never pays for it.
$(BUILD)/obj/cmplog/vinyl/$(call ir_objname,$(1)): $(1)
	@mkdir -p $$(@D)
	AFL_LLVM_CMPLOG=1 $(AFL_CC) $(CFLAGS_CMPLOG) $(CFLAGS_IR_EXTRA) -I$(LEAN_INC) -MMD -MP -c $$< -o $$@
endef
$(foreach f,$(IR_SRCS),$(eval $(call IR_RULE,$(f))))

IR_OBJS_FUZZ    := $(foreach f,$(IR_SRCS),$(BUILD)/obj/fuzz/vinyl/$(call ir_objname,$(f)))
IR_OBJS_AFL     := $(foreach f,$(IR_SRCS),$(BUILD)/obj/afl/vinyl/$(call ir_objname,$(f)))
IR_OBJS_COVFUZZ := $(foreach f,$(IR_SRCS),$(BUILD)/obj/covfuzz/vinyl/$(call ir_objname,$(f)))
IR_OBJS_CMPLOG  := $(foreach f,$(IR_SRCS),$(BUILD)/obj/cmplog/vinyl/$(call ir_objname,$(f)))

$(BUILD)/lib/libvinyl.fuzz.a: $(IR_OBJS_FUZZ)
	@mkdir -p $(@D)
	rm -f $@ && ar rcs $@ $^

$(BUILD)/lib/libvinyl.afl.a: $(IR_OBJS_AFL)
	@mkdir -p $(@D)
	rm -f $@ && ar rcs $@ $^

$(BUILD)/lib/libvinyl.cmplog.a: $(IR_OBJS_CMPLOG)
	@mkdir -p $(@D)
	rm -f $@ && ar rcs $@ $^

$(BUILD)/lib/libvinyl.covfuzz.a: $(IR_OBJS_COVFUZZ)
	@mkdir -p $(@D)
	rm -f $@ && ar rcs $@ $^
